version: '3.9'

services:
  server:
    build:
      context: ./udp-server
      dockerfile: Dockerfile
    container_name: server
    networks:
      - udpnet

  attacker:
    image: python:3.9-slim
    container_name: attacker
    networks:
      - udpnet
    volumes:
      - ./udp-client:/app
    working_dir: /app
    command: ["python3", "ataque_udp.py"]

  benign:
    image: python:3.9-slim
    container_name: benign-client
    networks:
      - udpnet
    volumes:
      - ./udp-client:/app
    working_dir: /app
    command: ["python3", "benigno_udp.py"]

networks:
  udpnet:
    driver: bridge
